CREATE TABLE USUARIO(
	IDUSUARIO		UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	EMAIL			NVARCHAR(100)		NOT NULL UNIQUE,
	SENHA			NVARCHAR(40)		NOT NULL,
	DATACRIACAO		DATETIME			NOT NULL,
	PRIMARY KEY(IDUSUARIO))
GO

CREATE TABLE CONTATO(
	IDCONTATO		UNIQUEIDENTIFIER		NOT NULL,
	NOME			NVARCHAR(150)			NOT NULL,
	TELEFONE		NVARCHAR(20)			NOT NULL,
	EMAIL			NVARCHAR(100)			NOT NULL,
	DATANASCIMENTO	DATE					NOT NULL,
	TIPO			INTEGER					NOT NULL,
	IDUSUARIO		UNIQUEIDENTIFIER		NOT NULL,
	PRIMARY KEY(IDCONTATO),
	FOREIGN KEY(IDUSUARIO)
		REFERENCES USUARIO(IDUSUARIO))
GO